name: Lint
on: push

jobs:
  test:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load node_modules cache
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.yarnrc.yml') }}

      - name: Load yarn cache
        uses: actions/cache@v3
        id: cache-yarn
        with:
          path: |
            **/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.yarnrc.yml') }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true' || steps.cache-yarn.outputs.cache-hit != 'true'
        run: |
          yarn install

      - name: Run lint
        run: yarn lint
